# Configuração Starship com estética Cyberpunk e efeito diagonal
format = """
[](#0D0221)\
$os\
[](bg:#340042 fg:#0D0221)\
$username\
[](bg:#3B1F54 fg:#340042)\
$directory\
[](fg:#3B1F54 bg:none)\
$fill\
[](bg:none fg:#9331FF)\
$git_branch\
$git_status\
[](fg:#9331FF bg:#00F6FF)\
$nodejs\
$python\
$rust\
$golang\
[](fg:#00F6FF bg:#FF0097)\
$time\
[](fg:#FF0097 bg:none)\
$line_break\
$character
"""

# Configurações gerais
command_timeout = 5000

# Módulo fill para criar espaço entre as seções esquerda e direita
[fill]
symbol = " "
style = "bg:none"

# Caractere de prompt
[character]
success_symbol = "[↯](bold #36F9F6)"
error_symbol = "[✗](bold #FF073A)"
vimcmd_symbol = "[V](bold #64D7D2)"

# Sistema operacional
[os]
format = "[$symbol](bg:#0D0221 fg:#F706CF) "
disabled = false

[os.symbols]
Windows = "󰍲"
Macos = "󰀵"
Linux = "󰌽"
Ubuntu = "󰕈"
Debian = "󰣚"
Raspbian = "󰐿"
Mint = "󰣭"
Fedora = "󰣛"
CentOS = "󰣨"
Alpine = "󰣿"
Arch = "󰣇"
Amazon = "󰣴"

# Nome de usuário 
[username]
style_user = "bg:#340042 fg:#FF00F5 bold"
style_root = "bg:#340042 fg:#FF073A bold"
format = '[$user ]($style)'
disabled = false
show_always = true

# Diretório atual
[directory]
style = "bg:#3B1F54 fg:#C7F8FF bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " "
read_only_style = "bg:#3B1F54 fg:#FF073A"

# Branch Git
[git_branch]
symbol = "󱓞 "
style = "bg:#9331FF fg:#000000 bold"
format = '[ $symbol$branch ]($style)'
truncation_length = 20
truncation_symbol = "…"

# Status Git
[git_status]
style = "bg:#9331FF fg:#121212"
format = '[$all_status$ahead_behind ]($style)'
conflicted = "⚠️ "
ahead = "⟫${count} "
behind = "⟪${count} "
diverged = "⥮${ahead_count}⥯${behind_count} "
untracked = "◌${count} "
stashed = "✱${count} "
modified = "✶${count} "
staged = "✓${count} "
renamed = "⟿${count} "
deleted = "✘${count} "

# Hora
[time]
disabled = false
time_format = "%H:%M"
style = "bg:#FF0097 fg:#000000 bold"
format = '[ 󱑍 $time ]($style)'

# Node.js
[nodejs]
symbol = "󰎙 "
style = "bg:#00F6FF fg:#000000"
format = '[ $symbol($version) ]($style)'
detect_extensions = ["js", "jsx", "ts", "tsx", "mjs", "cjs"]
detect_files = ["package.json", ".node-version", ".nvmrc"]
detect_folders = ["node_modules"]

# Python
[python]
symbol = "󰌠 "
style = "bg:#00F6FF fg:#000000"
format = '[ $symbol($version) ]($style)'
detect_extensions = ["py", "pyc", "pyd"]
detect_files = ["requirements.txt", "pyproject.toml", "Pipfile", "__init__.py"]
detect_folders = [".venv", "venv", ".env", "env"]

# Rust
[rust]
symbol = "󱘗 "
style = "bg:#00F6FF fg:#000000"
format = '[ $symbol($version) ]($style)'
detect_extensions = ["rs"]
detect_files = ["Cargo.toml"]

# Go
[golang]
symbol = "󰟓 "
style = "bg:#00F6FF fg:#000000"
format = '[ $symbol($version) ]($style)'
detect_extensions = ["go"]
detect_files = ["go.mod", "go.sum", "go.work", "main.go"]
detect_folders = ["Godeps"]

# Java
[java]
symbol = "󰬷 "
style = "bg:#00F6FF fg:#000000"
format = '[ $symbol($version) ]($style)'
detect_extensions = ["java", "class", "jar", "gradle", "clj", "cljc"]
detect_files = ["pom.xml", "build.gradle", ".java-version"]
detect_folders = [".java"]

# Kotlin
[kotlin]
symbol = "󱈙 "
style = "bg:#00F6FF fg:#000000"
format = '[ $symbol($version) ]($style)'
detect_extensions = ["kt", "kts"]
detect_files = ["build.gradle.kts"]

# PHP
[php]
symbol = "󰌟 "
style = "bg:#00F6FF fg:#000000"
format = '[ $symbol($version) ]($style)'
detect_extensions = ["php", "phps", "php.stub", "phtml"]
detect_files = ["composer.json", ".php-version"]
detect_folders = ["composer.json"]

# Ruby
[ruby]
symbol = "󰴭 "
style = "bg:#00F6FF fg:#000000"
format = '[ $symbol($version) ]($style)'
detect_extensions = ["rb"]
detect_files = ["Gemfile", ".ruby-version"]
detect_folders = [".rbenv"]

# Docker context
[docker_context]
symbol = "󰡨 "
style = "bg:#00F6FF fg:#000000"
format = '[ $symbol$context ]($style)'
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = ["docker"]

# Bateria (ativo apenas quando baixa)
[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
format = "[$symbol$percentage]($style) "
disabled = false

[[battery.display]]
threshold = 30
style = "bold #FF0097"

# Comando anterior falhou?
[status]
format = "[$symbol$status]($style) "
disabled = false
symbol = "⚠️ "
style = "bold #FF0097"
