# Configuração do Starship personalizada
# Com base na configuração existente e melhorias de design

# Configurações globais
add_newline = true
command_timeout = 3600  # Timeout aumentado para comandos (1 hora)
scan_timeout = 500

# Layout principal do prompt
format = """
[┌─](bold #CF9FFF)\
\b  \
$username[@](bold #CF9FFF)\
$hostname [in](#fdfe02) \
$directory\
$git_branch\
$git_status\
$fill\
$docker_context\
$package\
$nodejs\
$python\
$rust\
$golang\
$java\
$lua\
$php\
$kotlin\
$c\
$dart\
$memory_usage\
$aws\
$gcloud\
$azure\
\b $time
[└─$character](bold #CF9FFF)
"""

# Caractere de prompt
[character]
success_symbol = "[❯](bold #00aaff)"
error_symbol = "[✗](bold red)"

# Configurações do nome de usuário
[username]
disabled = false
style_root = "bold red"
style_user = "bold #CCCCFF"
format = "[$user]($style)"
show_always = true

# Configurações do hostname
[hostname]
disabled = false
style = "bold #00aaff"
format = "[$hostname]($style)"
ssh_only = false
ssh_symbol = " "

# Preenchimento (fill) para espaçar à direita
[fill]
symbol = " "
style = "bold #313131"

# Diretório atual
[directory]
style = "bold #00aaff"
truncation_length = 3
truncation_symbol = "⋯/"
read_only = " 󰌾"
format = "[$path]($style)[$read_only]($read_only_style) "

# Tempo de execução do comando
[cmd_duration]
disabled = false
min_time = 500
format = "[$duration]($style) "
style = "yellow"

# Hora atual
[time]
disabled = false
use_12hr = false
style = "bold #CF9FFF"
format = "[$time]($style)"
time_format = "%H:%M:%S"

# IP local
[localip]
ssh_only = false
disabled = false
format = "on [$localipv4](bold red)"

# Configurações Git
# 1. Otimize o módulo git_status para evitar operações custosas
[git_status]
style = "bold yellow"
format = '[$all_status$ahead_behind]($style) '
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = false
stashed = "*"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"
# Adicione estas novas opções:
disabled = false
ignore_submodules = true  # Ignora submódulos para melhor performance
windows_starship = true   # Otimiza para Windows/WSL (ajuda mesmo no macOS)

# 2. Adicione o módulo git_metrics para melhor performance com cache
[git_metrics]
disabled = false  # Habilita o módulo git_metrics
added_style = "bold green"
deleted_style = "bold red"
only_nonzero_diffs = true  # Só mostra quando há diferenças
format = "([+$added]($added_style) [-$deleted]($deleted_style) )"

# 3. Otimize o módulo git_branch para reduzir chamadas ao git
[git_branch]
symbol = " "
style = "bold purple"
format = "[$symbol$branch]($style) "
# Adicione estas novas opções:
always_show_remote = false  # Evita consultas desnecessárias ao remote
truncation_length = 20      # Limita o tamanho do nome da branch
only_attached = true        # Só mostra quando anexado a uma branch

# 4. Configure o módulo git_state para ser mais leve
[git_state]
format = '[\($state( $progress_current/$progress_total)\)]($style) '
cherry_pick = "🍒 PICKING"
disabled = false

# Linguagens e ferramentas - cores alinhadas
[docker_context]
symbol = " "
style = "blue"
format = "[$symbol$context]($style) "

[nodejs]
symbol = " "
style = "bold green"
format = "[$symbol$version]($style) "

[python]
symbol = " "
style = "bold blue"
format = "[$symbol$version]($style) "

[rust]
symbol = " "
style = "bold orange"
format = "[$symbol$version]($style) "

[golang]
symbol = " "
style = "bold cyan"
format = "[$symbol$version]($style) "

[java]
symbol = " "
style = "bold red"
format = "[$symbol$version]($style) "

[kotlin]
symbol = " "
style = "bold purple"
format = "[$symbol$version]($style) "

[lua]
symbol = " "
style = "bold blue"
format = "[$symbol$version]($style) "

[php]
symbol = " "
style = "bold purple"
format = "[$symbol$version]($style) "

[c]
symbol = " "
style = "bold blue"
format = "[$symbol$version]($style) "

[cmake]
symbol = "△ "
format = "[$symbol$version]($style) "

[dart]
symbol = " "
style = "bold blue"
format = "[$symbol$version]($style) "

[deno]
symbol = "🦕 "
format = "[$symbol$version]($style) "

[dotnet]
symbol = " "
format = "[$symbol$version]($style) "

[elixir]
symbol = " "
format = "[$symbol$version]($style) "

[elm]
symbol = " "
format = "[$symbol$version]($style) "

[guix_shell]
symbol = " "
format = "[$symbol$version]($style) "

[julia]
symbol = " "
format = "[$symbol$version]($style) "

[gradle]
symbol = " "
format = "[$symbol$version]($style) "

[perl]
symbol = " "
format = "[$symbol$version]($style) "

[ruby]
symbol = " "
format = "[$symbol$version]($style) "

[swift]
symbol = " "
format = "[$symbol$version]($style) "

[terraform]
symbol = "󱁢 "
format = "[$symbol$version]($style) "

# Cloud services
[aws]
symbol = "  "
style = "bold yellow"
format = "[$symbol$profile]($style) "

[gcloud]
symbol = " "
style = "bold blue"
format = "[$symbol$project]($style) "

[azure]
symbol = "󰠅 "
style = "bold blue"
format = "[$symbol$subscription]($style) "

[openstack]
symbol = " "
format = "[$symbol$cloud]($style) "

# Ferramentas e ambientes
[conda]
symbol = " "
format = "[$symbol$environment]($style) "

[meson]
symbol = "󰔷 "
format = "[$symbol$project]($style) "

[spack]
symbol = "🅢 "
format = "[$symbol$environment]($style) "

[memory_usage]
symbol = "󰍛 "
style = "bold dimmed green"
threshold = 75
format = "[$symbol${ram}]($style) "

# Sistemas operacionais
[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

# Outros símbolos
[package]
symbol = "󰏗 "
format = "[$symbol$version]($style) "

[fossil_branch]
symbol = " "

[hg_branch]
symbol = " "

[haskell]
symbol = " "
format = "[$symbol$version]($style) "

[haxe]
symbol = " "
format = "[$symbol$version]($style) "

[nim]
symbol = "󰆥 "
format = "[$symbol$version]($style) "

[nix_shell]
symbol = " "
format = "[$symbol$state]($style) "

[ocaml]
symbol = " "
format = "[$symbol$version]($style) "

[pijul_channel]
symbol = " "

[rlang]
symbol = "󰟔 "
format = "[$symbol$version]($style) "

[scala]
symbol = " "
format = "[$symbol$version]($style) "

[zig]
symbol = " "
format = "[$symbol$version]($style) "

[fennel]
symbol = " "
format = "[$symbol$version]($style) "

[buf]
symbol = " "
format = "[$symbol$version]($style) "

[crystal]
symbol = " "
format = "[$symbol$version]($style) "
