# Set the prefix to Control + A
set -g prefix C-a

# Remove the old prefix key binding
unbind C-b

# Send the prefix to the terminal
bind C-a send-prefix

# Start new windows at 1, not 0
set -g base-index 1

# Set the window index to be displayed in the status line
set -g window-status-current-format "#[fg=colour235,bg=colour27] #I #[fg=colour27,bg=colour235]#W "

# Move between panes with Control + hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes with Control + Alt + hjkl
bind -n C-h resize-pane -L 5
bind -n C-j resize-pane -D 5
bind -n C-k resize-pane -U 5
bind -n C-l resize-pane -R 5

# Split panes using | and -
bind | split-window -h
bind - split-window -v

# Reload the tmux config file
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded TMUX config"

# Enable mouse mode
set -g mouse on
mouse=n

