# Generated by Powerlevel10k configuration wizard on 2025-05-13 at 22:41 -03.
# Based on romkatv/powerlevel10k/config/p10k-rainbow.zsh, checksum 4117.
# Wizard options: nerdfont-v3 + powerline, small icons, rainbow, unicode, 24h time,
# slanted separators, slanted heads, slanted tails, 2 lines, disconnected, left frame,
# light-ornaments, sparse, many icons, concise, transient_prompt,
# instant_prompt=verbose.
# Type `p10k configure` to generate another config.
#
# MODIFIED FOR KANAGAWA DRAGON THEME
#
# Config for Powerlevel10k with powerline prompt style with colorful background.
# Type `p10k configure` to generate your own config based on it.
#
# Tip: Looking for a nice color? Here's a one-liner to print colormap.
#
#   for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%16)):#15}:+$'\n'}; done

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'       ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'       ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options. This allows you to apply configuration changes without
  # restarting zsh. Edit ~/.p10k.zsh and type `source ~/.p10k.zsh`.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required.
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # The list of segments shown on the left. Fill it with the most important segments.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    os_icon                 # os identifier
    dir                     # current directory
    vcs                     # git status
    # =========================[ Line #2 ]=========================
    newline                 # \n
    prompt_char             # prompt symbol (WAS REMOVED IN ORIGINAL, ADDED BACK FOR KANAGAWA)
  )

  # The list of segments shown on the right. Fill it with less important segments.
  # Right prompt on the last prompt line (where you are typing your commands) gets
  # automatically hidden when the input line reaches it. Right prompt above the
  # last prompt line gets hidden if it would overlap with left prompt.
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    status                  # exit code of the last command
    command_execution_time  # duration of the last command
    background_jobs         # presence of background jobs
    direnv                  # direnv status (https://direnv.net/)
    asdf                    # asdf version manager (https://github.com/asdf-vm/asdf)
    virtualenv              # python virtual environment (https://docs.python.org/3/library/venv.html)
    anaconda                # conda environment (https://conda.io/)
    pyenv                   # python environment (https://github.com/pyenv/pyenv)
    goenv                   # go environment (https://github.com/syndbg/goenv)
    nodenv                  # node.js version from nodenv (https://github.com/nodenv/nodenv)
    nvm                     # node.js version from nvm (https://github.com/nvm-sh/nvm)
    nodeenv                 # node.js environment (https://github.com/ekalinin/nodeenv)
    # node_version          # node.js version
    # go_version            # go version (https://golang.org)
    # rust_version          # rustc version (https://www.rust-lang.org)
    # dotnet_version        # .NET version (https://dotnet.microsoft.com)
    # php_version           # php version (https://www.php.net/)
    # laravel_version       # laravel php framework version (https://laravel.com/)
    # java_version          # java version (https://www.java.com/)
    # package               # name@version from package.json (https://docs.npmjs.com/files/package.json)
    rbenv                   # ruby version from rbenv (https://github.com/rbenv/rbenv)
    rvm                     # ruby version from rvm (https://rvm.io)
    fvm                     # flutter version management (https://github.com/leoafarias/fvm)
    luaenv                  # lua version from luaenv (https://github.com/cehoffman/luaenv)
    jenv                    # java version from jenv (https://github.com/jenv/jenv)
    plenv                   # perl version from plenv (https://github.com/tokuhirom/plenv)
    perlbrew                # perl version from perlbrew (https://github.com/gugod/App-perlbrew)
    phpenv                  # php version from phpenv (https://github.com/phpenv/phpenv)
    scalaenv                # scala version from scalaenv (https://github.com/scalaenv/scalaenv)
    haskell_stack           # haskell version from stack (https://haskellstack.org/)
    kubecontext             # current kubernetes context (https://kubernetes.io/)
    terraform               # terraform workspace (https://www.terraform.io)
    # terraform_version     # terraform version (https://www.terraform.io)
    aws                     # aws profile (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html)
    aws_eb_env              # aws elastic beanstalk environment (https://aws.amazon.com/elasticbeanstalk/)
    azure                   # azure account name (https://docs.microsoft.com/en-us/cli/azure)
    gcloud                  # google cloud cli account and project (https://cloud.google.com/)
    google_app_cred         # google application credentials (https://cloud.google.com/docs/authentication/production)
    toolbox                 # toolbox name (https://github.com/containers/toolbox)
    context                 # user@hostname
    nordvpn                 # nordvpn connection status, linux only (https://nordvpn.com/)
    ranger                  # ranger shell (https://github.com/ranger/ranger)
    nnn                     # nnn shell (https://github.com/jarun/nnn)
    lf                      # lf shell (https://github.com/gokcehan/lf)
    xplr                    # xplr shell (https://github.com/sayanarijit/xplr)
    vim_shell               # vim shell indicator (:sh)
    midnight_commander      # midnight commander shell (https://midnight-commander.org/)
    nix_shell               # nix shell (https://nixos.org/nixos/nix-pills/developing-with-nix-shell.html)
    chezmoi_shell           # chezmoi shell (https://www.chezmoi.io/)
    vi_mode                 # vi mode (you don't need this if you've enabled prompt_char)
    # vpn_ip                # virtual private network indicator
    # load                  # CPU load
    # disk_usage            # disk usage
    # ram                   # free RAM
    # swap                  # used swap
    todo                    # todo items (https://github.com/todotxt/todo.txt-cli)
    timewarrior             # timewarrior tracking status (https://timewarrior.net/)
    taskwarrior             # taskwarrior task count (https://taskwarrior.org/)
    per_directory_history   # Oh My Zsh per-directory-history local/global indicator
    # cpu_arch              # CPU architecture
    time                    # current time
    # =========================[ Line #2 ]=========================
    newline
    # ip                    # ip address and bandwidth usage for a specified network interface
    # public_ip             # public IP address
    # proxy                 # system-wide http/https/ftp proxy
    # battery               # internal battery
    # wifi                  # wifi speed
    # example               # example user-defined segment (see prompt_example function below)
  )

  # Defines character set used by powerlevel10k. It's best to let `p10k configure` set it for you.
  typeset -g POWERLEVEL9K_MODE=nerdfont-v3
  # When set to `moderate`, some icons will have an extra space after them. This is meant to avoid
  # icon overlap when using non-monospace fonts. When set to `none`, spaces are not added.
  typeset -g POWERLEVEL9K_ICON_PADDING=none

  # When set to true, icons appear before content on both sides of the prompt. When set
  # to false, icons go after content. If empty or not set, icons go before content in the left
  # prompt and after content in the right prompt.
  typeset -g POWERLEVEL9K_ICON_BEFORE_CONTENT=

  # Add an empty line before each prompt.
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

  # Connect left prompt lines with these symbols.
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%F{240}╭─%f'
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX='%F{240}├─%f'
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%F{240}╰─%f'
  # Connect right prompt lines with these symbols.
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=

  # Filler between left and right prompt on the first prompt line.
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' '
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_GAP_BACKGROUND=
  if [[ $POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR != ' ' ]]; then
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=239
    typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='%{%}'
    typeset -g POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}'
  fi

  # Separator between same-color segments on the left.
  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\u2571'
  # Separator between same-color segments on the right.
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\u2571'
  # Separator between different-color segments on the left.
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0BC'
  # Separator between different-color segments on the right.
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0BA'

  # The right end of left prompt.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0BC'
  # The left end of right prompt.
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0BA'
  # The left end of left prompt.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0BA'
  # The right end of right prompt.
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0BC'
  # Left prompt terminator for lines without any segments.
  typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=

  #################################[ os_icon: os identifier ]##################################
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=254 # FujiWhite
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=033 # Wave Blue
  # typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='⭐'

  ################################[ prompt_char: prompt symbol ]################################
  typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND= # Transparent
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=071   # Kanagawa Spring Green
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=160 # Kanagawa Carp Red
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_{LEFT,RIGHT}_WHITESPACE=

  ##################################[ dir: current directory ]##################################
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=237     # Kanagawa Dark Gray (Sumi Ink)
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=110     # Kanagawa OniViolet (or a light blue like 073)
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=245 # Kanagawa Light Gray (FujiGray)
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=188     # Kanagawa FujiWhite (or a highlight like 108 Spring Green)
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  local anchor_files=(
    .bzr .citc .git .hg .node-version .python-version .go-version .ruby-version .lua-version
    .java-version .perl-version .php-version .tool-versions .shorten_folder_marker .svn
    .terraform CVS Cargo.toml composer.json go.mod package.json stack.yaml
  )
  typeset -g POWERLEVEL9K_SHORTEN_FOLDER_MARKER="(${(j:|:)anchor_files})"
  typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
  typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=50
  typeset -g POWERLEVEL9K_DIR_HYPERLINK=false
  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3
  # typeset -g POWERLEVEL9K_DIR_CLASSES=()
  # typeset -g POWERLEVEL9K_DIR_PREFIX='in '

  #####################################[ vcs: git status ]######################################
  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=071       # Kanagawa Spring Green / Wave Aqua
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=172    # Kanagawa Carp Orange / Autumn Orange
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=220   # Kanagawa Carp Yellow / Wave Yellow
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=160  # Kanagawa Carp Red / Sakura Pink
  typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND=239     # Kanagawa Soft Gray

  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'

  function my_git_formatter() {
    emulate -L zsh
    if [[ -n $P9K_CONTENT ]]; then
      typeset -g my_git_format=$P9K_CONTENT
      return
    fi

    local       meta='%F{254}' # FujiWhite (for branch name, tag, commit hash, etc.)
    local      clean='%F{232}' # Dark text on Clean BG (e.g., Spring Green)
    local   modified='%F{232}' # Dark text on Modified BG (e.g., Carp Orange)
    local  untracked='%F{232}' # Dark text on Untracked BG (e.g., Carp Yellow)
    local conflicted='%F{254}' # Light text on Conflicted BG (e.g., Carp Red)

    local res
    if [[ -n $VCS_STATUS_LOCAL_BRANCH ]]; then
      local branch=${(V)VCS_STATUS_LOCAL_BRANCH}
      (( $#branch > 32 )) && branch[13,-13]="…"
      res+="${meta}${(g::)POWERLEVEL9K_VCS_BRANCH_ICON}${branch//\%/%%}" # Meta color for branch icon and name
    fi
    if [[ -n $VCS_STATUS_TAG && -z $VCS_STATUS_LOCAL_BRANCH ]]; then
      local tag=${(V)VCS_STATUS_TAG}
      (( $#tag > 32 )) && tag[13,-13]="…"
      res+="${meta}#${tag//\%/%%}" # Meta color for tag
    fi
    [[ -z $VCS_STATUS_LOCAL_BRANCH && -z $VCS_STATUS_TAG ]] &&
      res+="${meta}@${VCS_STATUS_COMMIT[1,8]}" # Meta color for commit
    if [[ -n ${VCS_STATUS_REMOTE_BRANCH:#$VCS_STATUS_LOCAL_BRANCH} ]]; then
      res+="${meta}:${(V)VCS_STATUS_REMOTE_BRANCH//\%/%%}" # Meta color for remote branch
    fi
    if [[ $VCS_STATUS_COMMIT_SUMMARY == (|*[^[:alnum:]])(wip|WIP)(|[^[:alnum:]]*) ]]; then
      res+=" ${modified}wip" # Modified FG for "wip"
    fi
    if (( VCS_STATUS_COMMITS_AHEAD || VCS_STATUS_COMMITS_BEHIND )); then
      (( VCS_STATUS_COMMITS_BEHIND )) && res+=" ${clean}⇣${VCS_STATUS_COMMITS_BEHIND}" # Clean FG for behind
      (( VCS_STATUS_COMMITS_AHEAD && !VCS_STATUS_COMMITS_BEHIND )) && res+=" "
      (( VCS_STATUS_COMMITS_AHEAD  )) && res+="${clean}⇡${VCS_STATUS_COMMITS_AHEAD}" # Clean FG for ahead
    elif [[ -n $VCS_STATUS_REMOTE_BRANCH ]]; then
      # res+=" ${clean}=" # Example: up to date with remote
    fi
    (( VCS_STATUS_PUSH_COMMITS_BEHIND )) && res+=" ${clean}⇠${VCS_STATUS_PUSH_COMMITS_BEHIND}"
    (( VCS_STATUS_PUSH_COMMITS_AHEAD && !VCS_STATUS_PUSH_COMMITS_BEHIND )) && res+=" "
    (( VCS_STATUS_PUSH_COMMITS_AHEAD  )) && res+="${clean}⇢${VCS_STATUS_PUSH_COMMITS_AHEAD}"
    (( VCS_STATUS_STASHES        )) && res+=" ${clean}*${VCS_STATUS_STASHES}" # Clean FG for stashes
    [[ -n $VCS_STATUS_ACTION     ]] && res+=" ${conflicted}${VCS_STATUS_ACTION}" # Conflicted FG for action
    (( VCS_STATUS_NUM_CONFLICTED )) && res+=" ${conflicted}~${VCS_STATUS_NUM_CONFLICTED}" # Conflicted FG for num conflicted
    (( VCS_STATUS_NUM_STAGED     )) && res+=" ${modified}+${VCS_STATUS_NUM_STAGED}" # Modified FG for num staged
    (( VCS_STATUS_NUM_UNSTAGED   )) && res+=" ${modified}!${VCS_STATUS_NUM_UNSTAGED}" # Modified FG for num unstaged
    (( VCS_STATUS_NUM_UNTRACKED  )) && res+=" ${untracked}${(g::)POWERLEVEL9K_VCS_UNTRACKED_ICON}${VCS_STATUS_NUM_UNTRACKED}" # Untracked FG for num untracked
    (( VCS_STATUS_HAS_UNSTAGED == -1 )) && res+=" ${modified}─" # Modified FG for unknown
    typeset -g my_git_format=$res
  }
  functions -M my_git_formatter 2>/dev/null
  typeset -g POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=-1
  typeset -g POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN='~'
  typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true
  typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION='${$((my_git_formatter()))+${my_git_format}}'
  typeset -g POWERLEVEL9K_VCS_{STAGED,UNSTAGED,UNTRACKED,CONFLICTED,COMMITS_AHEAD,COMMITS_BEHIND}_MAX_NUM=-1
  typeset -g POWERLEVEL9K_VCS_BACKENDS=(git)

  ##########################[ status: exit code of the last command ]###########################
  typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
  typeset -g POWERLEVEL9K_STATUS_OK=true
  typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✔'
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=071 # Kanagawa Spring Green
  typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=235 # Kanagawa Main BG (or omit for transparent)
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION='✔'
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=071
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=235
  typeset -g POWERLEVEL9K_STATUS_ERROR=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=160 # Kanagawa Carp Red
  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=235
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
  typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION='✘'
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=160
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=235
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION='✘'
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=160
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND=235

  ###################[ command_execution_time: duration of the last command ]###################
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=232 # Kanagawa Dark Text
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=220 # Kanagawa Carp Yellow
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'

  #######################[ background_jobs: presence of background jobs ]#######################
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=254 # Kanagawa FujiWhite
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=099 # Kanagawa Oni Violet
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false

  #######################[ direnv: direnv status (https://direnv.net/) ]########################
  typeset -g POWERLEVEL9K_DIRENV_FOREGROUND=188 # Kanagawa FujiWhite
  typeset -g POWERLEVEL9K_DIRENV_BACKGROUND=237 # Kanagawa Dark Gray (consistent with dir)

  ###############[ asdf: asdf version manager (https://github.com/asdf-vm/asdf) ]###############
  typeset -g POWERLEVEL9K_ASDF_FOREGROUND=188     # Kanagawa FujiWhite
  typeset -g POWERLEVEL9K_ASDF_BACKGROUND=236     # Kanagawa Dark Gray (Secondary)
  typeset -g POWERLEVEL9K_ASDF_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_ASDF_SHOW_SYSTEM=true
  typeset -g POWERLEVEL9K_ASDF_SHOW_ON_UPGLOB=
  typeset -g POWERLEVEL9K_ASDF_RUBY_FOREGROUND=232
  typeset -g POWERLEVEL9K_ASDF_RUBY_BACKGROUND=160 # Kanagawa Carp Red
  typeset -g POWERLEVEL9K_ASDF_PYTHON_FOREGROUND=232
  typeset -g POWERLEVEL9K_ASDF_PYTHON_BACKGROUND=073 # Kanagawa Python Blue
  typeset -g POWERLEVEL9K_ASDF_GOLANG_FOREGROUND=232
  typeset -g POWERLEVEL9K_ASDF_GOLANG_BACKGROUND=067 # Kanagawa Go Blue
  typeset -g POWERLEVEL9K_ASDF_NODEJS_FOREGROUND=232
  typeset -g POWERLEVEL9K_ASDF_NODEJS_BACKGROUND=108 # Kanagawa Node Green
  typeset -g POWERLEVEL9K_ASDF_RUST_FOREGROUND=232
  typeset -g POWERLEVEL9K_ASDF_RUST_BACKGROUND=172   # Kanagawa Rust Orange
  typeset -g POWERLEVEL9K_ASDF_DOTNET_CORE_FOREGROUND=254
  typeset -g POWERLEVEL9K_ASDF_DOTNET_CORE_BACKGROUND=099 # Kanagawa .NET Violet
  typeset -g POWERLEVEL9K_ASDF_FLUTTER_FOREGROUND=232
  typeset -g POWERLEVEL9K_ASDF_FLUTTER_BACKGROUND=073 # Kanagawa Flutter Blue
  typeset -g POWERLEVEL9K_ASDF_LUA_FOREGROUND=254
  typeset -g POWERLEVEL9K_ASDF_LUA_BACKGROUND=110   # Kanagawa Lua Dark Violet/Blue
  typeset -g POWERLEVEL9K_ASDF_JAVA_FOREGROUND=232
  typeset -g POWERLEVEL9K_ASDF_JAVA_BACKGROUND=208   # Kanagawa Java Orange/Yellow
  typeset -g POWERLEVEL9K_ASDF_PERL_FOREGROUND=254
  typeset -g POWERLEVEL9K_ASDF_PERL_BACKGROUND=033   # Kanagawa Perl Deep Blue
  typeset -g POWERLEVEL9K_ASDF_ERLANG_FOREGROUND=254
  typeset -g POWERLEVEL9K_ASDF_ERLANG_BACKGROUND=160 # Kanagawa Erlang Red
  typeset -g POWERLEVEL9K_ASDF_ELIXIR_FOREGROUND=254
  typeset -g POWERLEVEL9K_ASDF_ELIXIR_BACKGROUND=099 # Kanagawa Elixir Violet
  typeset -g POWERLEVEL9K_ASDF_POSTGRES_FOREGROUND=254
  typeset -g POWERLEVEL9K_ASDF_POSTGRES_BACKGROUND=067 # Kanagawa Postgres Blue
  typeset -g POWERLEVEL9K_ASDF_PHP_FOREGROUND=232
  typeset -g POWERLEVEL9K_ASDF_PHP_BACKGROUND=135   # Kanagawa PHP Light Violet
  typeset -g POWERLEVEL9K_ASDF_HASKELL_FOREGROUND=254
  typeset -g POWERLEVEL9K_ASDF_HASKELL_BACKGROUND=172 # Kanagawa Haskell Orange
  typeset -g POWERLEVEL9K_ASDF_JULIA_FOREGROUND=232
  typeset -g POWERLEVEL9K_ASDF_JULIA_BACKGROUND=108   # Kanagawa Julia Green

  ##########[ nordvpn: nordvpn connection status, linux only (https://nordvpn.com/) ]###########
  typeset -g POWERLEVEL9K_NORDVPN_FOREGROUND=254 # FujiWhite
  typeset -g POWERLEVEL9K_NORDVPN_BACKGROUND=067 # Wave Blue
  typeset -g POWERLEVEL9K_NORDVPN_{DISCONNECTED,CONNECTING,DISCONNECTING}_CONTENT_EXPANSION=
  typeset -g POWERLEVEL9K_NORDVPN_{DISCONNECTED,CONNECTING,DISCONNECTING}_VISUAL_IDENTIFIER_EXPANSION=

  #################[ ranger: ranger shell (https://github.com/ranger/ranger) ]##################
  typeset -g POWERLEVEL9K_RANGER_FOREGROUND=188 # FujiWhite
  typeset -g POWERLEVEL9K_RANGER_BACKGROUND=237 # Dark Gray

  ######################[ nnn: nnn shell (https://github.com/jarun/nnn) ]#######################
  typeset -g POWERLEVEL9K_NNN_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_NNN_BACKGROUND=108 # Spring Green

  ######################[ lf: lf shell (https://github.com/gokcehan/lf) ]#######################
  typeset -g POWERLEVEL9K_LF_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_LF_BACKGROUND=108 # Spring Green

  ##################[ xplr: xplr shell (https://github.com/sayanarijit/xplr) ]##################
  typeset -g POWERLEVEL9K_XPLR_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_XPLR_BACKGROUND=108 # Spring Green

  ###########################[ vim_shell: vim shell indicator (:sh) ]###########################
  typeset -g POWERLEVEL9K_VIM_SHELL_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_VIM_SHELL_BACKGROUND=071 # Wave Aqua / Spring Green

  ######[ midnight_commander: midnight commander shell (https://midnight-commander.org/) ]######
  typeset -g POWERLEVEL9K_MIDNIGHT_COMMANDER_FOREGROUND=188 # FujiWhite
  typeset -g POWERLEVEL9K_MIDNIGHT_COMMANDER_BACKGROUND=237 # Dark Gray

  #[ nix_shell: nix shell (https://nixos.org/nixos/nix-pills/developing-with-nix-shell.html) ]##
  typeset -g POWERLEVEL9K_NIX_SHELL_FOREGROUND=254 # FujiWhite
  typeset -g POWERLEVEL9K_NIX_SHELL_BACKGROUND=067 # Wave Blue

  ##################[ chezmoi_shell: chezmoi shell (https://www.chezmoi.io/) ]##################
  typeset -g POWERLEVEL9K_CHEZMOI_SHELL_FOREGROUND=254 # FujiWhite
  typeset -g POWERLEVEL9K_CHEZMOI_SHELL_BACKGROUND=073 # Lighter Blue

  ##################################[ disk_usage: disk usage ]##################################
  typeset -g POWERLEVEL9K_DISK_USAGE_NORMAL_FOREGROUND=071    # Spring Green
  typeset -g POWERLEVEL9K_DISK_USAGE_NORMAL_BACKGROUND=236    # Dark Gray Secondary
  typeset -g POWERLEVEL9K_DISK_USAGE_WARNING_FOREGROUND=232   # Dark Text
  typeset -g POWERLEVEL9K_DISK_USAGE_WARNING_BACKGROUND=220   # Carp Yellow
  typeset -g POWERLEVEL9K_DISK_USAGE_CRITICAL_FOREGROUND=254  # FujiWhite
  typeset -g POWERLEVEL9K_DISK_USAGE_CRITICAL_BACKGROUND=160  # Carp Red
  typeset -g POWERLEVEL9K_DISK_USAGE_WARNING_LEVEL=90
  typeset -g POWERLEVEL9K_DISK_USAGE_CRITICAL_LEVEL=95
  typeset -g POWERLEVEL9K_DISK_USAGE_ONLY_WARNING=false

  ###########[ vi_mode: vi mode (you don't need this if you've enabled prompt_char) ]###########
  typeset -g POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND=071   # Spring Green
  typeset -g POWERLEVEL9K_VI_MODE_FOREGROUND=232          # Dark Text (for normal mode text on green BG)
  typeset -g POWERLEVEL9K_VI_COMMAND_MODE_STRING=NORMAL
  typeset -g POWERLEVEL9K_VI_VISUAL_MODE_STRING=VISUAL
  typeset -g POWERLEVEL9K_VI_MODE_VISUAL_BACKGROUND=067   # Wave Blue
  # For VISUAL_BACKGROUND, if text is default (black/dark), it's fine. If you set text color, use 254 for light text.
  typeset -g POWERLEVEL9K_VI_OVERWRITE_MODE_STRING=OVERTYPE
  typeset -g POWERLEVEL9K_VI_MODE_OVERWRITE_BACKGROUND=220 # Carp Yellow
  # For OVERWRITE_BACKGROUND, if text is default (black/dark), it's fine. If you set text color, use 232 for dark text.
  typeset -g POWERLEVEL9K_VI_INSERT_MODE_STRING=
  typeset -g POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND=245 # Light Gray (FujiGray) for insert mode (no BG)

  ######################################[ ram: free RAM ]#######################################
  typeset -g POWERLEVEL9K_RAM_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_RAM_BACKGROUND=220 # Carp Yellow

  #####################################[ swap: used swap ]######################################
  typeset -g POWERLEVEL9K_SWAP_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_SWAP_BACKGROUND=220 # Carp Yellow

  ######################################[ load: CPU load ]######################################
  typeset -g POWERLEVEL9K_LOAD_WHICH=5
  typeset -g POWERLEVEL9K_LOAD_NORMAL_FOREGROUND=232   # Dark Text
  typeset -g POWERLEVEL9K_LOAD_NORMAL_BACKGROUND=071   # Spring Green
  typeset -g POWERLEVEL9K_LOAD_WARNING_FOREGROUND=232  # Dark Text
  typeset -g POWERLEVEL9K_LOAD_WARNING_BACKGROUND=220  # Carp Yellow
  typeset -g POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND=254 # FujiWhite
  typeset -g POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND=160 # Carp Red

  ################[ todo: todo items (https://github.com/todotxt/todo.txt-cli) ]################
  typeset -g POWERLEVEL9K_TODO_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_TODO_BACKGROUND=245 # FujiGray (light gray BG)
  typeset -g POWERLEVEL9K_TODO_HIDE_ZERO_TOTAL=true
  typeset -g POWERLEVEL9K_TODO_HIDE_ZERO_FILTERED=false

  ###########[ timewarrior: timewarrior tracking status (https://timewarrior.net/) ]############
  typeset -g POWERLEVEL9K_TIMEWARRIOR_FOREGROUND=254 # FujiWhite
  typeset -g POWERLEVEL9K_TIMEWARRIOR_BACKGROUND=238 # Darker Gray
  typeset -g POWERLEVEL9K_TIMEWARRIOR_CONTENT_EXPANSION='${P9K_CONTENT:0:24}${${P9K_CONTENT:24}:+…}'

  ##############[ taskwarrior: taskwarrior task count (https://taskwarrior.org/) ]##############
  typeset -g POWERLEVEL9K_TASKWARRIOR_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_TASKWARRIOR_BACKGROUND=110 # OniViolet

  ######[ per_directory_history: Oh My Zsh per-directory-history local/global indicator ]#######
  typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_LOCAL_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_LOCAL_BACKGROUND=073 # Lighter Blue
  typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_GLOBAL_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_GLOBAL_BACKGROUND=239 # Soft Gray

  ################################[ cpu_arch: CPU architecture ]################################
  typeset -g POWERLEVEL9K_CPU_ARCH_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_CPU_ARCH_BACKGROUND=239 # Soft Gray

  ##################################[ context: user@hostname ]##################################
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=160 # Kanagawa Carp Red
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=235 # Kanagawa Main BG
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=172 # Kanagawa Carp Orange
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_BACKGROUND=235 # Kanagawa Main BG
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=245 # Kanagawa FujiGray (Light Gray)
  typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=235 # Kanagawa Main BG
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=

  ###[ virtualenv: python virtual environment (https://docs.python.org/3/library/venv.html) ]###
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=073 # Kanagawa Python Blue
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=false
  typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=

  ######################[ anaconda: conda environment (https://conda.io/) ]######################
  typeset -g POWERLEVEL9K_ANACONDA_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_ANACONDA_BACKGROUND=073 # Kanagawa Python Blue (consistent)
  typeset -g POWERLEVEL9K_ANACONDA_CONTENT_EXPANSION='${${${${CONDA_PROMPT_MODIFIER#\(}% }%\)}:-${CONDA_PREFIX:t}}'

  ################[ pyenv: python environment (https://github.com/pyenv/pyenv) ]################
  typeset -g POWERLEVEL9K_PYENV_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_PYENV_BACKGROUND=073 # Kanagawa Python Blue
  typeset -g POWERLEVEL9K_PYENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_PYENV_SHOW_SYSTEM=true
  typeset -g POWERLEVEL9K_PYENV_CONTENT_EXPANSION='${P9K_CONTENT}${${P9K_CONTENT:#$P9K_PYENV_PYTHON_VERSION(|/*)}:+ $P9K_PYENV_PYTHON_VERSION}'

  ################[ goenv: go environment (https://github.com/syndbg/goenv) ]################
  typeset -g POWERLEVEL9K_GOENV_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_GOENV_BACKGROUND=067 # Kanagawa Go Blue
  typeset -g POWERLEVEL9K_GOENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_GOENV_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_GOENV_SHOW_SYSTEM=true

  ##########[ nodenv: node.js version from nodenv (https://github.com/nodenv/nodenv) ]##########
  typeset -g POWERLEVEL9K_NODENV_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_NODENV_BACKGROUND=108 # Kanagawa Node Green
  typeset -g POWERLEVEL9K_NODENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_NODENV_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_NODENV_SHOW_SYSTEM=true

  ##############[ nvm: node.js version from nvm (https://github.com/nvm-sh/nvm) ]###############
  typeset -g POWERLEVEL9K_NVM_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_NVM_BACKGROUND=108 # Kanagawa Node Green
  typeset -g POWERLEVEL9K_NVM_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_NVM_SHOW_SYSTEM=true

  ############[ nodeenv: node.js environment (https://github.com/ekalinin/nodeenv) ]############
  typeset -g POWERLEVEL9K_NODEENV_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_NODEENV_BACKGROUND=108 # Kanagawa Node Green
  typeset -g POWERLEVEL9K_NODEENV_SHOW_NODE_VERSION=false
  typeset -g POWERLEVEL9K_NODEENV_{LEFT,RIGHT}_DELIMITER=

  ##############################[ node_version: node.js version ]###############################
  # typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=254 # FujiWhite
  # typeset -g POWERLEVEL9K_NODE_VERSION_BACKGROUND=108 # Kanagawa Node Green
  # typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true

  #######################[ go_version: go version (https://golang.org) ]########################
  # typeset -g POWERLEVEL9K_GO_VERSION_FOREGROUND=254 # FujiWhite
  # typeset -g POWERLEVEL9K_GO_VERSION_BACKGROUND=067 # Kanagawa Go Blue
  # typeset -g POWERLEVEL9K_GO_VERSION_PROJECT_ONLY=true

  #################[ rust_version: rustc version (https://www.rust-lang.org) ]##################
  # typeset -g POWERLEVEL9K_RUST_VERSION_FOREGROUND=232 # Dark Text
  # typeset -g POWERLEVEL9K_RUST_VERSION_BACKGROUND=172 # Kanagawa Rust Orange
  # typeset -g POWERLEVEL9K_RUST_VERSION_PROJECT_ONLY=true

  ###############[ dotnet_version: .NET version (https://dotnet.microsoft.com) ]################
  # typeset -g POWERLEVEL9K_DOTNET_VERSION_FOREGROUND=254 # FujiWhite
  # typeset -g POWERLEVEL9K_DOTNET_VERSION_BACKGROUND=099 # Kanagawa .NET Violet
  # typeset -g POWERLEVEL9K_DOTNET_VERSION_PROJECT_ONLY=true

  #####################[ php_version: php version (https://www.php.net/) ]######################
  # typeset -g POWERLEVEL9K_PHP_VERSION_FOREGROUND=232 # Dark Text
  # typeset -g POWERLEVEL9K_PHP_VERSION_BACKGROUND=135 # Kanagawa PHP Light Violet
  # typeset -g POWERLEVEL9K_PHP_VERSION_PROJECT_ONLY=true

  ##########[ laravel_version: laravel php framework version (https://laravel.com/) ]###########
  # typeset -g POWERLEVEL9K_LARAVEL_VERSION_FOREGROUND=254 # FujiWhite
  # typeset -g POWERLEVEL9K_LARAVEL_VERSION_BACKGROUND=160 # Kanagawa Laravel Red
  
  #############[ rbenv: ruby version from rbenv (https://github.com/rbenv/rbenv) ]##############
  typeset -g POWERLEVEL9K_RBENV_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_RBENV_BACKGROUND=160 # Kanagawa Ruby Red
  typeset -g POWERLEVEL9K_RBENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_RBENV_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_RBENV_SHOW_SYSTEM=true

  ####################[ java_version: java version (https://www.java.com/) ]####################
  # typeset -g POWERLEVEL9K_JAVA_VERSION_FOREGROUND=232 # Dark Text
  # typeset -g POWERLEVEL9K_JAVA_VERSION_BACKGROUND=208 # Kanagawa Java Orange/Yellow
  # typeset -g POWERLEVEL9K_JAVA_VERSION_PROJECT_ONLY=true
  # typeset -g POWERLEVEL9K_JAVA_VERSION_FULL=false

  ###[ package: name@version from package.json (https://docs.npmjs.com/files/package.json) ]####
  # typeset -g POWERLEVEL9K_PACKAGE_FOREGROUND=232 # Dark Text
  # typeset -g POWERLEVEL9K_PACKAGE_BACKGROUND=117 # Kanagawa Crystal Blue/Pinkish

  #######################[ rvm: ruby version from rvm (https://rvm.io) ]########################
  typeset -g POWERLEVEL9K_RVM_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_RVM_BACKGROUND=160 # Kanagawa Ruby Red
  typeset -g POWERLEVEL9K_RVM_SHOW_GEMSET=false
  typeset -g POWERLEVEL9K_RVM_SHOW_PREFIX=false

  ###########[ fvm: flutter version management (https://github.com/leoafarias/fvm) ]############
  typeset -g POWERLEVEL9K_FVM_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_FVM_BACKGROUND=073 # Kanagawa Flutter Blue

  ##########[ luaenv: lua version from luaenv (https://github.com/cehoffman/luaenv) ]###########
  typeset -g POWERLEVEL9K_LUAENV_FOREGROUND=254 # FujiWhite
  typeset -g POWERLEVEL9K_LUAENV_BACKGROUND=110 # Kanagawa Lua Dark Violet/Blue
  typeset -g POWERLEVEL9K_LUAENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_LUAENV_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_LUAENV_SHOW_SYSTEM=true

  ###############[ jenv: java version from jenv (https://github.com/jenv/jenv) ]################
  typeset -g POWERLEVEL9K_JENV_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_JENV_BACKGROUND=208 # Kanagawa Java Orange/Yellow
  typeset -g POWERLEVEL9K_JENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_JENV_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_JENV_SHOW_SYSTEM=true

  ###########[ plenv: perl version from plenv (https://github.com/tokuhirom/plenv) ]############
  typeset -g POWERLEVEL9K_PLENV_FOREGROUND=254 # FujiWhite
  typeset -g POWERLEVEL9K_PLENV_BACKGROUND=033 # Kanagawa Perl Deep Blue
  typeset -g POWERLEVEL9K_PLENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_PLENV_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_PLENV_SHOW_SYSTEM=true
  
  ##########[ perlbrew: perl version from perlbrew (https://github.com/gugod/App-perlbrew) ]############
  typeset -g POWERLEVEL9K_PERLBREW_FOREGROUND=254 # FujiWhite
  typeset -g POWERLEVEL9K_PERLBREW_BACKGROUND=033 # Kanagawa Perl Deep Blue
  typeset -g POWERLEVEL9K_PERLBREW_PROJECT_ONLY=true
  typeset -g POWERLEVEL9K_PERLBREW_SHOW_PREFIX=false

  ############[ phpenv: php version from phpenv (https://github.com/phpenv/phpenv) ]############
  typeset -g POWERLEVEL9K_PHPENV_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_PHPENV_BACKGROUND=135 # Kanagawa PHP Light Violet
  typeset -g POWERLEVEL9K_PHPENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_PHPENV_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_PHPENV_SHOW_SYSTEM=true

  #######[ scalaenv: scala version from scalaenv (https://github.com/scalaenv/scalaenv) ]#######
  typeset -g POWERLEVEL9K_SCALAENV_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_SCALAENV_BACKGROUND=160 # Kanagawa Scala Red
  typeset -g POWERLEVEL9K_SCALAENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_SCALAENV_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_SCALAENV_SHOW_SYSTEM=true

  ##########[ haskell_stack: haskell version from stack (https://haskellstack.org/) ]###########
  typeset -g POWERLEVEL9K_HASKELL_STACK_FOREGROUND=254 # FujiWhite
  typeset -g POWERLEVEL9K_HASKELL_STACK_BACKGROUND=172 # Kanagawa Haskell Orange
  typeset -g POWERLEVEL9K_HASKELL_STACK_SOURCES=(shell local)
  typeset -g POWERLEVEL9K_HASKELL_STACK_ALWAYS_SHOW=true

  ################[ terraform: terraform workspace (https://www.terraform.io) ]#################
  typeset -g POWERLEVEL9K_TERRAFORM_SHOW_DEFAULT=false
  typeset -g POWERLEVEL9K_TERRAFORM_CLASSES=( '*' OTHER)
  typeset -g POWERLEVEL9K_TERRAFORM_OTHER_FOREGROUND=108 # Kanagawa Spring Green
  typeset -g POWERLEVEL9K_TERRAFORM_OTHER_BACKGROUND=236 # Kanagawa Dark Gray Secondary

  #############[ terraform_version: terraform version (https://www.terraform.io) ]##############
  # typeset -g POWERLEVEL9K_TERRAFORM_VERSION_FOREGROUND=108 # Kanagawa Spring Green
  # typeset -g POWERLEVEL9K_TERRAFORM_VERSION_BACKGROUND=236 # Kanagawa Dark Gray Secondary
  # typeset -g POWERLEVEL9K_TERRAFORM_VERSION_SHOW_ON_COMMAND='terraform|tf'

  #############[ kubecontext: current kubernetes context (https://kubernetes.io/) ]#############
  typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|helm|kubens|kubectx|oc|istioctl|kogito|k9s|helmfile|flux|fluxctl|stern|kubeseal|skaffold|kubent|kubecolor|cmctl|sparkctl'
  typeset -g POWERLEVEL9K_KUBECONTEXT_CLASSES=( '*' DEFAULT)
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=254 # FujiWhite
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND=067 # Kanagawa Wave Blue / Sumi Ink
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION=
  POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION+='${P9K_KUBECONTEXT_CLOUD_CLUSTER:-${P9K_KUBECONTEXT_NAME}}'
  POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION+='${${:-/$P9K_KUBECONTEXT_NAMESPACE}:#/default}'

  #[ aws: aws profile (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html) ]#
  typeset -g POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|awless|cdk|terraform|pulumi|terragrunt'
  typeset -g POWERLEVEL9K_AWS_CLASSES=( '*' DEFAULT)
  typeset -g POWERLEVEL9K_AWS_DEFAULT_FOREGROUND=254 # FujiWhite
  typeset -g POWERLEVEL9K_AWS_DEFAULT_BACKGROUND=208 # Kanagawa Autumn Orange
  typeset -g POWERLEVEL9K_AWS_CONTENT_EXPANSION='${P9K_AWS_PROFILE//\%/%%}${P9K_AWS_REGION:+ ${P9K_AWS_REGION//\%/%%}}'

  #[ aws_eb_env: aws elastic beanstalk environment (https://aws.amazon.com/elasticbeanstalk/) ]#
  typeset -g POWERLEVEL9K_AWS_EB_ENV_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_AWS_EB_ENV_BACKGROUND=071 # Kanagawa Spring Green

  ##########[ azure: azure account name (https://docs.microsoft.com/en-us/cli/azure) ]##########
  typeset -g POWERLEVEL9K_AZURE_SHOW_ON_COMMAND='az|terraform|pulumi|terragrunt'
  typeset -g POWERLEVEL9K_AZURE_CLASSES=( '*' OTHER)
  typeset -g POWERLEVEL9K_AZURE_OTHER_FOREGROUND=254 # FujiWhite
  typeset -g POWERLEVEL9K_AZURE_OTHER_BACKGROUND=073 # Kanagawa Azure Blue

  ##########[ gcloud: google cloud account and project (https://cloud.google.com/) ]###########
  typeset -g POWERLEVEL9K_GCLOUD_SHOW_ON_COMMAND='gcloud|gcs|gsutil'
  typeset -g POWERLEVEL9K_GCLOUD_FOREGROUND=254 # FujiWhite
  typeset -g POWERLEVEL9K_GCLOUD_BACKGROUND=067 # Kanagawa Dark Blue (Wave/Sumi)
  typeset -g POWERLEVEL9K_GCLOUD_PARTIAL_CONTENT_EXPANSION='${P9K_GCLOUD_PROJECT_ID//\%/%%}'
  typeset -g POWERLEVEL9K_GCLOUD_COMPLETE_CONTENT_EXPANSION='${P9K_GCLOUD_PROJECT_NAME//\%/%%}'
  typeset -g POWERLEVEL9K_GCLOUD_REFRESH_PROJECT_NAME_SECONDS=60

  #[ google_app_cred: google application credentials (https://cloud.google.com/docs/authentication/production) ]#
  typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_SHOW_ON_COMMAND='terraform|pulumi|terragrunt'
  typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_CLASSES=( '*' DEFAULT)
  typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_FOREGROUND=254 # FujiWhite
  typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_BACKGROUND=220 # Kanagawa Wave Yellow
  typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_CONTENT_EXPANSION='${P9K_GOOGLE_APP_CRED_PROJECT_ID//\%/%%}'

  ##############[ toolbox: toolbox name (https://github.com/containers/toolbox) ]###############
  typeset -g POWERLEVEL9K_TOOLBOX_FOREGROUND=232 # Dark Text
  typeset -g POWERLEVEL9K_TOOLBOX_BACKGROUND=239 # Soft Gray
  typeset -g POWERLEVEL9K_TOOLBOX_CONTENT_EXPANSION='${P9K_TOOLBOX_NAME:#fedora-toolbox-*}'

  ###############################[ public_ip: public IP address ]###############################
  # typeset -g POWERLEVEL9K_PUBLIC_IP_FOREGROUND=245 # FujiGray
  # typeset -g POWERLEVEL9K_PUBLIC_IP_BACKGROUND=235 # Main BG (or omit)

  ########################[ vpn_ip: virtual private network indicator ]#########################
  # typeset -g POWERLEVEL9K_VPN_IP_FOREGROUND=232 # Dark Text
  # typeset -g POWERLEVEL9K_VPN_IP_BACKGROUND=073 # Lighter Blue
  # typeset -g POWERLEVEL9K_VPN_IP_CONTENT_EXPANSION=
  # typeset -g POWERLEVEL9K_VPN_IP_INTERFACE='(gpd|wg|(.*tun)|tailscale)[0-9]*|(zt.*)'
  # typeset -g POWERLEVEL9K_VPN_IP_SHOW_ALL=false

  ###########[ ip: ip address and bandwidth usage for a specified network interface ]###########
  # typeset -g POWERLEVEL9K_IP_BACKGROUND=067 # Dark Blue
  # typeset -g POWERLEVEL9K_IP_FOREGROUND=232 # Dark Text
  # typeset -g POWERLEVEL9K_IP_CONTENT_EXPANSION='${P9K_IP_RX_RATE:+⇣$P9K_IP_RX_RATE }${P9K_IP_TX_RATE:+⇡$P9K_IP_TX_RATE }$P9K_IP_IP'
  # typeset -g POWERLEVEL9K_IP_INTERFACE='[ew].*'

  ##########################[ proxy: system-wide http/https/ftp proxy ]##########################
  # typeset -g POWERLEVEL9K_PROXY_FOREGROUND=245 # FujiGray
  # typeset -g POWERLEVEL9K_PROXY_BACKGROUND=236 # Dark Gray Secondary

  ################################[ battery: internal battery ]#################################
  typeset -g POWERLEVEL9K_BATTERY_LOW_THRESHOLD=20
  typeset -g POWERLEVEL9K_BATTERY_LOW_FOREGROUND=160  # Kanagawa Carp Red
  typeset -g POWERLEVEL9K_BATTERY_{CHARGING,CHARGED}_FOREGROUND=071 # Kanagawa Spring Green
  typeset -g POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND=220 # Kanagawa Carp Yellow
  typeset -g POWERLEVEL9K_BATTERY_STAGES='\UF008E\UF007A\UF007B\UF007C\UF007D\UF007E\UF007F\UF0080\UF0081\UF0082\UF0079'
  typeset -g POWERLEVEL9K_BATTERY_VERBOSE=false
  typeset -g POWERLEVEL9K_BATTERY_BACKGROUND=235 # Main BG (or omit)

  #####################################[ wifi: wifi speed ]#####################################
  # typeset -g POWERLEVEL9K_WIFI_FOREGROUND=232 # Dark Text
  # typeset -g POWERLEVEL9K_WIFI_BACKGROUND=073 # Lighter Blue

  ####################################[ time: current time ]####################################
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=188     # Kanagawa FujiWhite
  typeset -g POWERLEVEL9K_TIME_BACKGROUND=238     # Kanagawa Darker Gray (Sumi Ink variation)
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false

  function prompt_example() {
    p10k segment -b 160 -f 254 -i '⭐' -t 'Kanagawa, %n' # Example: Red BG, White FG
  }
  function instant_prompt_example() {
    prompt_example
  }
  typeset -g POWERLEVEL9K_EXAMPLE_FOREGROUND=254
  typeset -g POWERLEVEL9K_EXAMPLE_BACKGROUND=160

  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true
  (( ! $+functions[p10k] )) || p10k reload
}
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}
(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
