name: Auto create PRs when Pushing

on:
  push:
    branches:
      - feature/*
env:
  BRANCH_NAME: ${{ github.head_ref }}
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        run: |
          PAYLOAD=$(cat <<EOF
            {
              "title": "Title of my PR",
              "body": "Automated PR to ...",
              "head": "${BRANCH_NAME}",
              "base": "main"
            }
          EOF
          )
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
