name: Auto create PRs when Pushing

on:
  push:
    branches:
      - feature/*
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GitHub CLI
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        run: gh pr create -a @me -B main --title 'Automatic PR creation to merge into main' --body 'Created an automatic Pull Request using Github CLI'
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
      
      - name: Check for PR creation
        run: |
          pr_url=$(gh pr list --json url | jq -r '.[].url')
          if [ -z "$pr_url" ]; then
            echo "Failed to create pull request."
            exit 1
          fi

      - name: Extract PR number
        id: extract_pr_number
        run: echo "::set-output name=pr_number::$(echo $pr_url | cut -d'/' -f 7)"
      
      - name: Check for merge conflicts
        run: gh pr check --exit-code ${{ steps.extract_pr_number.outputs.pr_number }}
      
      - name: Merge PR
        run: |
          pr_number=${{ steps.extract_pr_number.outputs.pr_number }}
          gh pr merge $pr_number --auto
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
